CREATE TABLE IF NOT EXISTS files_db.file_details (
	id BIGINT UNSIGNED auto_increment NOT NULL,
    tag SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	name VARCHAR(255) NOT NULL,
	path VARCHAR(255) NOT NULL,
    file_type VARCHAR(255) NOT NULL,
    size BIGINT UNSIGNED NOT NULL,
	uploaded_at TIMESTAMP NOT NULL,
	uploader_id BIGINT UNSIGNED NOT NULL,
	group_id BIGINT UNSIGNED NOT NULL,
	CONSTRAINT events_pk PRIMARY KEY (id)
);